import { useEffect, useState } from "react";
import ChartConverterService from "../../services/chartConverter";
import { logGenerationStackConfig } from "../../configs/ChartConfig";
import { LogGenerationChartDataType } from "./models/ChartDataType";
import ReactECharts, { EChartsOption } from "echarts-for-react";
import { generateChartData } from "@/services/helper";

const StackChartCont = ({ id, data }: { id: string, data: LogGenerationChartDataType[] }) => {
  const [chartConfigs, setChartConfig] = useState<EChartsOption>();

  useEffect(() => {
    const { categories, messages, errors } = ChartConverterService.formatLogGenerationData(data);
    const seriesData = [
      { name: 'Info', data: messages },
      { name: 'Error', data: errors }
    ];
    const configData: EChartsOption = generateChartData(logGenerationStackConfig, categories, seriesData, 'bar');
    setChartConfig(configData);
  }, [data]);

  return (
    <>
      <div className="flex flex-col h-[50vh]">
        <div className="text-[var(--text-color-primary)] text-xs px-4 pt-4">Logs generated by Components in last 24H</div>
        <div className="grow">
          <div className="flex justify-between space-x-4 p-4 h-full">
            {chartConfigs && (
              <div className="flex-1 h-full">
                <ReactECharts option={chartConfigs} style={{ width: "100%", height: "100%" }}
                  opts={{ renderer: "canvas" }} />
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default StackChartCont;
