import { create } from "@mui/material/styles/createTransitions";
import { get } from "react-hook-form";

export const ApiPaths: Record<string, string> = {
  login: "/loginNnp",
  logout: "/logout",
  getUsers: "/eiimp/userDetails/:envId",
  getUserDetails: "/eiimp/userDetails/:userId",
  postUser: "/eiimp/user",
  getFeatures: "/feature/v2/:envId",
  getFeatureElements: "/feaelem/v2/:feaId",
  getChildElements: "/chelementdtl/v2/:elementId/:userId",
  last24UsageMemory: "/portal/last24UsageMemory/:envId",
  last24Log: "/portal/last24Log/:envId",
  last24PipelineUsage: "/portal/last24PipelineUsage/:envId",
  last24ApiGatewayUsage: "/portal/last24ApiGatewayUsage/:envId",
  subscribedComponentUrl: "/accounts/subscribedComponents?accountName=:accountName",
  billingDetailsUrl: "/accounts/billingDetails?accountName=:accountName",
  marketplaceContributionUrl: "/nnp-login/dummy/marketplace-contribution.json",
  accountCommunicationUrl: "/accounts/communications?accountName=:accountName",
  // allPlansUrl: "/nnp-login/dummy/all-plan-list.json",
  userListUrl: "/user/read/user/v2/env/:envId/status/active",
  openIssuesUrl: "/support/issues?pageNumber=:pageNumber&pageSize=:pageSize&accName=:accName&issueStatus=OPEN",
  pastIssuesUrl: "/support/issues?pageNumber=:pageNumber&pageSize=:pageSize&accName=:accName&issueStatus=CLOSED",
  issueTrendUrl: "/support/issues/trends?accName=:envId",
  getIssueCategoriesType: "/all/domval?domainName=issueCategory",
  getIssueCategories: "/all/domval?domainName=parentIssue",
  getIssuePriority: "/all/domval?domainName=priority",
  getIssueStatus: "/all/domval?domainName=status",
  createIssue: "/support/create",
  updateIssue: "/support/update/:id",
  getCountries: "/acc/read/country/all",
  getOrgCategories: "/all/domval?domainName=org-category",
  getPlans: "/env/read/plan",
  getPlanComp: "/env/read/plan/:planId/comp",
  userExist: "/acc/check/exists/user/:userId",
  accExist: "/acc/check/exists/account/:account",
  userEmailExists: "/user/exists?userIdentifier=:email",
  checkExistsAllSystems: "/user/exists/v3?userIdentifier=:userIdentifier&envId=:envId",
  register: "/acc/register/account",
  registerFree: "/acc/register/free/",
  registerUser: "/user/register/user/v3",
  updateUser: "/portal/user",
  payment: "/trigger",
  registerPayment: "/acc/register/payment",
  getEnvFeatureAccess: "/user/read/access/v3/env/:envId/user/:userId",
  updateUserAccess: "/user/update/access/v3/env/:envId/user/:userId",
  getUserRole: "/user/read/roles/v2",
  getStatus: "/all/domval?domainName=commonStatus",
  getK8sDetails: "/pods/details?envName=:envId",
  restartPod: "/pod?envName=:envId&podName=:podName",
  getAccountDetails: "/accounts/details?accountName=:envId",
  putAccountDetails: "/accounts/details/:envId",
  getProxyConfig: "/accounts/proxyConfig",
  addProxyConfig: "/accounts/proxyConfig",
  updateProxyConfig: "/accounts/proxyConfig/:envConfigId",
  deleteProxyConfig: "/accounts/proxyConfig/:envConfigId",
  k8IntgResources: "/associated/deployment/resources?deploymentName=:deploymentName&envName=:envId",
  deleteResources: "/delete/resources",
  openKubernetesTerminal: "/terminal",
  getAccWithCountry: "/account/:envId"
};
